# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Client(object):
    def setupUi(self, Client):
        Client.setObjectName("Client")
        Client.resize(490, 530)
        self.centralwidget = QtWidgets.QWidget(Client)
        self.centralwidget.setObjectName("centralwidget")
        self.le_host = QtWidgets.QLineEdit(self.centralwidget)
        self.le_host.setGeometry(QtCore.QRect(50, 30, 113, 20))
        self.le_host.setObjectName("le_host")
        self.pb_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pb_connect.setGeometry(QtCore.QRect(170, 30, 51, 23))
        self.pb_connect.setObjectName("pb_connect")
        self.lbl_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_1.setGeometry(QtCore.QRect(20, 60, 31, 16))
        self.lbl_1.setObjectName("lbl_1")
        self.lv_clients = QtWidgets.QListView(self.centralwidget)
        self.lv_clients.setGeometry(QtCore.QRect(290, 150, 181, 281))
        self.lv_clients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_clients.setObjectName("lv_clients")
        self.lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_2.setGeometry(QtCore.QRect(20, 130, 51, 16))
        self.lbl_2.setObjectName("lbl_2")
        self.lbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_3.setGeometry(QtCore.QRect(290, 130, 41, 16))
        self.lbl_3.setObjectName("lbl_3")
        self.lbl_selected_client = QtWidgets.QLabel(self.centralwidget)
        self.lbl_selected_client.setGeometry(QtCore.QRect(290, 450, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_selected_client.setFont(font)
        self.lbl_selected_client.setAutoFillBackground(False)
        self.lbl_selected_client.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_selected_client.setText("")
        self.lbl_selected_client.setObjectName("lbl_selected_client")
        self.pb_send = QtWidgets.QPushButton(self.centralwidget)
        self.pb_send.setGeometry(QtCore.QRect(230, 450, 41, 23))
        self.pb_send.setObjectName("pb_send")
        self.te_output = QtWidgets.QTextEdit(self.centralwidget)
        self.te_output.setGeometry(QtCore.QRect(20, 150, 251, 281))
        self.te_output.setObjectName("te_output")
        self.te_input = QtWidgets.QTextEdit(self.centralwidget)
        self.te_input.setGeometry(QtCore.QRect(20, 440, 201, 31))
        self.te_input.setObjectName("te_input")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(273, 0, 16, 481))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 100, 281, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.le_email = QtWidgets.QLineEdit(self.centralwidget)
        self.le_email.setGeometry(QtCore.QRect(50, 60, 171, 20))
        self.le_email.setObjectName("le_email")
        self.lbl_4 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_4.setGeometry(QtCore.QRect(20, 30, 31, 16))
        self.lbl_4.setObjectName("lbl_4")
        Client.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Client)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 21))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        Client.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Client)
        self.statusbar.setObjectName("statusbar")
        Client.setStatusBar(self.statusbar)
        self.actionEZcomm_help = QtWidgets.QAction(Client)
        self.actionEZcomm_help.setObjectName("actionEZcomm_help")
        self.actionabout_EZcomm = QtWidgets.QAction(Client)
        self.actionabout_EZcomm.setObjectName("actionabout_EZcomm")
        self.menuhelp.addAction(self.actionEZcomm_help)
        self.menuhelp.addAction(self.actionabout_EZcomm)
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(Client)
        QtCore.QMetaObject.connectSlotsByName(Client)

    def retranslateUi(self, Client):
        _translate = QtCore.QCoreApplication.translate
        Client.setWindowTitle(_translate("Client", "EZcomm"))
        self.pb_connect.setText(_translate("Client", "connect"))
        self.lbl_1.setText(_translate("Client", "Email: "))
        self.lv_clients.setToolTip(_translate("Client", "clients list"))
        self.lbl_2.setText(_translate("Client", "Message:"))
        self.lbl_3.setText(_translate("Client", "Clients:"))
        self.lbl_selected_client.setToolTip(_translate("Client", "email"))
        self.pb_send.setText(_translate("Client", "send"))
        self.lbl_4.setText(_translate("Client", "Host: "))
        self.menuhelp.setTitle(_translate("Client", "help"))
        self.actionEZcomm_help.setText(_translate("Client", "EZcomm help"))
        self.actionabout_EZcomm.setText(_translate("Client", "about EZcomm"))
